# Generated by Django 4.1.2 on 2022-12-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_device_name_device_devicename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='assignedDevice',
        ),
        migrations.AddField(
            model_name='content',
            name='assignedDevice',
            field=models.ManyToManyField(to='myapp.device'),
        ),
    ]
