# Generated by Django 4.1.2 on 2022-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_content_assigneddevice_device_imageplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
